### PR TITLE
Add version-pinned requirements.txt file and install_requires.

### PR DESCRIPTION
**Pull request by aneeshusa**
Since distutils support is required, place the canonical requirements list in requirements.txt, and copy the requirements parser from the main salt repo to setup install_requires in case of setuptools.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Please also add six to the requirements.txt

**Comment by s0undt3ch** [comment]
Also, please don't place upper limits on the requirements. There's no need until we actually find a problem with them.

**Comment by aneeshusa** [comment]
Pylint already has a dependency on six, so it'll get pulled in automatically.

Here's my reasoning for adding upper limits based on how I use package management: (warning: big hunk of text)
- The requirements.txt file is a contract between developers and users: whenever you install this package, now or 20 years later, these versions will always work together.
- We can't guarantee that all future versions of our dependencies will work with the current salt-pylint version.
- Therefore, not having upper bounds could break the contract. Example:
  - Someone goes to install Salt i.e. 4 months after this salt-pylint release
  - Since that Salt release, some dependency e.g. pylint has put out a new, non-backwards compatible release.
  - Without upper limits here, the package manager will pull in the stable version of Salt and the new pylint.
  - They don't work together and the user is sad :disappointed:
- We can't go back in time 4 months ex post facto to add the upper bounds for this user, so we need to specify them now.
- If new, backwards-compatible versions of our dependencies come out, we can bump those versions and cut a new release to affirm to our users that those versions are also supported.
- The requirements.txt file doesn't say anything about other combinations: they might work, they might not. So a user on an older salt-pylint release that doesn't want to update salt-pylint can still update e.g. pylint themselves if they know those versions work together, regardless of requirements.txt's lack of input.

For me, it's more important to always uphold the dependency contract and ensure stability than to worry about not getting the latest dependency versions and features  or having to release more versions due to dependency version bumping.

To be fair, this doesn't matter as much for salt-pylint because it's just a linter and doesn't affect code correctness, and the python source code format is pretty stable.

Let me know how you feel about this.

**Comment by s0undt3ch** [comment]
I'll try this new approach. Thanks.

**Pull request merged**
