### PR TITLE
Add Windows support to the file permissions check

### PR DESCRIPTION
**Pull request by skizunov**

### CODE REVIEW

**Comment by skizunov** [comment]
@s0undt3ch @terminalmage : I am not sure if this repo is monitored for pull requests. Just to be sure, I wanted to ping you since it seems like you two have been the main contributors to this repo.

**Comment by mchugh19** [comment]
@twangboy thoughts?

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
@skizunov Do mind rebasing this?

@s0undt3ch This looks good to me? What do you think?

**Review by s0undt3ch — APPROVED** [review]
If the windows expert says it's good, it's good.

**Comment by skizunov** [comment]
@twangboy : Rebased

**Pull request merged**
